feat: implement caching
hpi-dhc/PharMe pull request #328
Opened 2022-05-31 10:01 UTC by kolioOtSofia

Closes #324 
Closes #166 
Closes #320 

- [x] I have read the [code-style guidelines](https://github.com/hpi-dhc/PharMe/blob/main/docs/FLUTTER_STYLE.md) and confirmed that this PR upholds said guidelines

---

## Changes

## Testing Changes

## Screenshot of Changes (Optional)

2022-06-02 20:59 UTC, Toalaah requested changes

2022-06-07 08:17 UTC, kolioOtSofia commented on app/lib/common/models/medication/guideline.dart
> +        cpicComment == other.cpicComment;
Yeah, but actually only the id is the parameter that does not to be changed. The reason is that, a changing the id in the backend for instance, does not mean that the guideline is different, however a change in something else, implies that this a different guideline

2022-06-07 08:20 UTC, kolioOtSofia commented on app/lib/common/models/medication/guideline.dart
> +class GenePhenotype {
Yeah, the reason for them being together in one file is that a `Guideline` consists of a `GenePhenotype`, `GeneSymbol` and `Phenotype` and they are only referenced here, so I would say that they are very closely related.

2022-06-07 08:20 UTC, kolioOtSofia commented on app/lib/common/models/medication/medication.dart
> +Iterable<int> idsFromHTTPResponse(Response resp) {
I dont know, the change came from main, will now make it a list :D

2022-06-07 11:38 UTC, Toalaah approved these changes

2022-06-08 08:13 UTC, merged