fix(app): filter user guidelines on medication detail screen
hpi-dhc/PharMe pull request #350
Opened 2022-06-07 10:53 UTC by DevSchmidtchen

Closes #348 

The problem wasn't the reports screen, but that the medication details screen didn't filter the guidelines based on the user. The displayed guidelines therefore was the random guideline which was first in the array.

- [x] I have read the [code-style guidelines](https://github.com/hpi-dhc/PharMe/blob/main/docs/FLUTTER_STYLE.md) and confirmed that this PR upholds said guidelines

---

## Changes

- make drugclass optional
- make guidelines optional
- filter user guidelines to not show random guideline

## Testing Changes

- test whether the information on the details screen matches those in the reports screen

2022-06-07 13:30 UTC, dieknolle3333 requested changes
thanks again for discovering this!

just making sure that we are all on the same page: do we need to show the disclaimer even if there are no guidelines? It feels kind of meaningless to say that only the genetic data was considered in the discovery that there are no guidelines for the user's genetic profile. Nevertheless, it seems important to convey that there are no guidelines according to the genetic data, but other implications due to other factors could exist. Maybe we can simply add this to the text that is shown when there are no guidelines, and omit the disclaimer card?

![Screenshot from 2022-06-07 15-22-22](https://user-images.githubusercontent.com/57364771/172391094-c7f40cb2-60e3-4737-a068-3d6814495ab0.png)

2022-06-07 13:30 UTC, dieknolle3333 commented on app/lib/common/pages/medications/medication.dart
> +          Text('No guidelines found matching your genetic profile.'),
so I propose adding something like 
`"medications_page_no_guidelines_for_phenotype": "No guidelines found matching your genetic profile.",` to lib/l10n/app_en.arb and using it like in l.50 above

2022-06-08 08:34 UTC, DevSchmidtchen commented
I just updated it according to your review @dieknolle3333. What do you think of this solution?

![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-06-08 at 10 32 42](https://user-images.githubusercontent.com/16440155/172570803-1caa1751-081b-4a53-94df-4fe66f2524a0.png)

2022-06-08 09:07 UTC, dieknolle3333 commented
> I just updated it according to your review @dieknolle3333. What do you think of this solution?
> 
> ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-06-08 at 10 32 42](https://user-images.githubusercontent.com/16440155/172570803-1caa1751-081b-4a53-94df-4fe66f2524a0.png)

I think this is better layout wise! I was wondering though whether we could update the lower text to something more fitting like "Please consult a medical professional to assess whether this medication is the right choice for you based on age, weight, and pre-existing condition". But maybe this is a seperate issue.

2022-06-09 11:49 UTC, SebastianWagner2 commented
> > I just updated it according to your review @dieknolle3333. What do you think of this solution?
> 
> I think this is better layout-wise! I was wondering though whether we could update the lower text to something more fitting like "Please consult a medical professional to assess whether this medication is the right choice for you based on age, weight, and pre-existing condition". But maybe this is a separate issue.

I would definitely revert the changes following your feedback on the PR. The screen looks very provisional now, even if me make an issue redesigning it in the case there are no guidelines provided, I would prefer the previous implementation

2022-06-10 11:05 UTC, SebastianWagner2 approved these changes

2022-06-13 08:21 UTC, merged