refactor: remove yarn.lock in sub-workspaces
hpi-dhc/PharMe pull request #353
Opened 2022-06-07 18:02 UTC by dieknolle3333

Closes #332

- [x] I have read the [code-style guidelines](https://github.com/hpi-dhc/PharMe/blob/main/docs/FLUTTER_STYLE.md) and confirmed that this PR upholds said guidelines

---

## Changes
This PR is literally just deleting the `yarn.lock` files in annotation server, lab server and in misc.

## Testing Changes
make sure everything (lab server, annotation server, misc. incl. jest badges, meeting assistant and interview analysis) is working properly

2022-06-07 19:56 UTC, jannis-baum requested changes
Good call spotting the badge generator and meeting assistant! I didn't think about those when I wrote the issue.

As far as I can tell, the badge generator and meeting assistance's lock files are still needed since they're not set up to be workspaces (see `package.json` in the repo's root).

To keep things working, we have to recover them or add the two subpackages as workspaces as well (this would be better IMO).

2022-06-07 20:38 UTC, dieknolle3333 commented
> Good call spotting the badge generator and meeting assistant! I didn't think about those when I wrote the issue.
> 
> As far as I can tell, the badge generator and meeting assistance's lock files are still needed since they're not set up to be workspaces (see `package.json` in the repo's root).
> 
> To keep things working, we have to recover them or add the two subpackages as workspaces as well (this would probably be better, maybe @Toalaah can give his thoughts on it?).

right, that makes sense. I un-deleted them for now and will wait for further opinions :)

2022-06-08 07:20 UTC, Toalaah requested changes
As @jannis-baum already mentioned, it is certainly not a bad idea to also add the miscellaneous packages to the workspaces (at the very least for the sake of consistency).

Also, please run `yarn` once in the repository root after adding the new workspaces. I am quite certain this is necessary as new dependencies will be tracked with the addition of the miscellaneous workspaces.

2022-06-08 09:42 UTC, Toalaah approved these changes

2022-06-08 15:17 UTC, merged