Validate dotenv, simplify dev setup
hpi-dhc/PharMe pull request #428
Opened 2022-07-27 12:47 UTC by Benjamin-Frost

Closes #373

- [x] I have read the [code-style guidelines](https://github.com/hpi-dhc/PharMe/blob/main/docs/FLUTTER_STYLE.md) and confirmed that this PR upholds said guidelines

2022-07-28 13:17 UTC, Toalaah requested changes

2022-07-28 13:17 UTC, Toalaah commented on .github/workflows/lab-server.yml
> +  DB_NAME: lab_server_db
```suggestion

```

2022-07-28 13:17 UTC, Toalaah commented on .github/workflows/lab-server.yml
> +          POSTGRES_DB: ${{ env.DB_NAME }}
```suggestion
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: lab_server_db
```

Makes it consistent with the annotation server CI file.

2022-07-28 13:17 UTC, Toalaah commented on annotation-server/.env.example
> +# Google Sheets
Is `EMPTY_GOOGLE_SHEET_ID` not also required if I want to be able to test my code locally?

2022-07-28 13:17 UTC, Toalaah commented on lab-server/.env.example
> +# Nothing is required for development.
```suggestion
```

2022-07-28 13:17 UTC, Toalaah commented on lab-server/.env.example
> +########## Required for Development ##########
```suggestion
```

2022-07-28 13:17 UTC, Toalaah commented on lab-server/.env.example
> +########## Additionally Required for Production ##########
```suggestion
########## The following environment variables may need to be adjusted for production environments ##########
```

2022-07-29 11:05 UTC, Toalaah approved these changes

2022-07-29 11:21 UTC, Benjamin-Frost commented on lab-server/src/common/validations/env.validation.ts
> +    KEYCLOAK_DB_NAME: Joi.string().default('keycloak_db'),
We just removed the local setup which makes this mandatory, no?

2022-07-29 11:36 UTC, Toalaah commented on lab-server/src/common/validations/env.validation.ts
> +    KEYCLOAK_DB_NAME: Joi.string().default('keycloak_db'),
Pretty sure the vars are only needed for the keycloak service in the docker compose. The lab server should never need the admin credentials to the UI / direct DB access.

2022-07-29 11:40 UTC, Benjamin-Frost commented on lab-server/src/common/validations/env.validation.ts
> +    KEYCLOAK_DB_NAME: Joi.string().default('keycloak_db'),
You are completely right, my bad

2022-07-29 11:42 UTC, merged