Improve app strings
hpi-dhc/PharMe pull request #437
Opened 2022-07-30 17:29 UTC by SebastianWagner2

Closes #436 

Also deletes all unused strings defined in app_en.arb

- [X] I have read the [code-style guidelines](https://github.com/hpi-dhc/PharMe/blob/main/docs/FLUTTER_STYLE.md) and confirmed that this PR upholds said guidelines

---

## Changes

## Testing Changes

## Screenshot of Changes (Optional)

2022-07-30 17:40 UTC, Toalaah requested changes

2022-07-30 17:40 UTC, Toalaah commented on app/lib/l10n/app_en.arb
> +  "medications_page_disclaimer": "This assessment is ONLY based on your genetics. Important factors like weight, age and pre-existing conditions are not considered.",
This all caps seems a little childish IMO. Also would change second sentence slightly + add oxford comma:

```suggestion
  "medications_page_disclaimer": "This assessment is only based on your genetics. Important factors such as weight, age, or pre-existing conditions are not considered.",
```

2022-07-30 17:40 UTC, Toalaah commented on app/lib/l10n/app_en.arb
> +  "medications_page_no_guidelines_for_phenotype": "We couldn't find a guideline matching your genetics.",
More formal.

```suggestion
  "medications_page_no_guidelines_for_phenotype": "We could not find a guideline matching your genetics.",
```

2022-07-30 17:40 UTC, Toalaah commented on app/lib/l10n/app_en.arb
> +  "medications_page_tooltip_classification": "The evidence level of a guideline represents how accepted it is by science. Guidelines with a lot of good studies supporting them have a high evidence le
```suggestion
  "medications_page_tooltip_classification": "The evidence level of a guideline represents how accepted it is by science. Guidelines supported by many reputable publications have a higher evidence level.",
```

2022-07-30 17:40 UTC, Toalaah commented on app/lib/l10n/app_en.arb
> +  "onboarding_3_disclaimer": "We DO NOT recommend medications for specific symptoms or illnesses!",
Again the all-caps thing but I guess at least you are being consistent. At this point no strong opinion I guess, so will leave this up to you.

2022-07-30 17:40 UTC, Toalaah commented on app/lib/l10n/app_en.arb
> +  "onboarding_4_text": "For PharMe to work, you need to get your genetics tested at a lab. You don't need an account to use PharMe: You can just sign in to the lab's website through our app.",
```suggestion
  "onboarding_4_text": "For PharMe to work, you must get your genetics tested at a lab. You do not need an account to use PharMe: Just sign in directly to your lab through our app in order to transfer your data.",
```

2022-07-30 17:40 UTC, Toalaah commented on app/lib/l10n/app_en.arb
> +  "onboarding_5_text": "After signing in to the lab, your genetic data is sent straight onto your phone.\n\nOur servers know nothing about you, neither your identity nor your genetics.",
```suggestion
  "onboarding_5_text": "After signing in to your chosen lab, your genetic data is transferred directly to your phone.\n\nOur servers never see any personally identifiable information. This includes both your identity and your genetic information.",
```

2022-07-30 17:40 UTC, Toalaah commented on app/lib/l10n/app_en.arb
> +  "reports_page_disclaimer_text": "All drugs listed here should be used with high caution. Consult your physician with these results before taking one of them. Click on a specific medication for deta
```suggestion
  "reports_page_disclaimer_text": "All drugs listed here should be used with high caution. Consult your physician with these results before taking one of them. Click on a specific medication to view more details.",
```

2022-07-31 10:36 UTC, LeonHermann322 approved these changes

2022-07-31 14:49 UTC, Toalaah approved these changes

2022-07-31 14:56 UTC, merged